# This is a config for E2B sandbox template.
# You can use template ID (dqesluptns167e9w4ktf) or template name (vibe-nextjs-c2igor) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-c2igor") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-c2igor") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-c2igor')

team_id = "d09ee986-7593-46c1-8dd4-1526d6f5d7f6"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-c2igor"
template_id = "dqesluptns167e9w4ktf"
